epochs: 5000
output_dir: output_dir

model:
  name: CoopVAEBM
  generator:
    name: Conv2d
    norm_type: batch
    input_nz: 100
    input_nc: 3
    output_nc: 3
    ngf: 64
    init_gain: 0.002
  ebm:
    name: Conv2d
    nef: 64
    input_sz: 32
    input_nc: 3
    output_nc: 100
    init_gain: 0.002
  encoder:
    name: Conv2d
    nef: 64
    norm_type: none
    init_gain: 0.002
  params:
    lambda_kl: 0.5

  mcmc:
    name: Langevin
    num_steps: 15
    step_size: 0.002
    refsig: 0.016    

dataset:
  train:
    name: CommonVisionDataset
    dataset_name: Cifar10
    dataroot: None
    batch_size: 250
    mode: train
    transforms:
      - name: Normalize
        mean: [127.5]
        std: [127.5]
        keys: [image]
  test:
    name: CommonVisionDataset
    dataset_name: Cifar10
    dataroot: None
    batch_size: 250
    mode: test
    transforms:
      - name: Normalize
        mean: [127.5]
        std: [127.5]
        keys: [image]

optimizer:
  optimVAE:
    name: Adam
    beta1: 0.5
    learning_rate: 0.0002
  optimEBM:
    name: Adam
    beta1: 0.5
    learning_rate: 0.009

log_config:
  interval: 100
  visiual_interval: 500
  samples_every_row: 10

snapshot_config:
  interval: 5